---
deployment:
  tasks:
    - export DEPLOYPATH1=/home/htdoffi1/minipos.htd-official.com
    - export DEPLOYPATH2=/home/htdoffi1/knb.htd-official.com
    - /bin/cp -a * $DEPLOYPATH1
    - /bin/cp -a * $DEPLOYPATH2
